version: '2.4'

x-base: &base
  build:
    context: .
    dockerfile: ./Dockerfile
    args:
      RUBY_VERSION: '3.1.4'
  tty: true
  restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
  stop_grace_period: "3s"
  environment:
    - DATABASE_HOST=postgres
    - DATABASE_PORT=5432
    - DATABASE_USERNAME=postgres
    - DATABASE_PASSWORD=postgresdb
    - REDIS_URL=redis://redis:6379/0
    - OPENAI_ACCESS_TOKEN==${OPENAI_ACCESS_TOKEN}
    - LASTFM_API_KEY=${LASTFM_API_KEY}
  depends_on:
    postgres:
      condition: service_healthy

services:
  app:
    <<: *base
    command: bin/rails server -p 3000 -b 0.0.0.0
    ports:
      - '3000:3000'
    healthcheck:
      test: curl --fail http://0.0.0.0:3000/up || exit 1
      retries: 3
      start_period: 10s

  postgres:
    image: postgres:14-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgresdb
    ports:
      - 5432
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "3s"
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

volumes:
  postgres: {}
