default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DATABASE_HOST', '0.0.0.0') %>
  port: <%= ENV.fetch('DATABASE_PORT', 5432) %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "postgresdb") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch("DATABASE_NAME", "webradio_development") %>

development:
  <<: *default
  database: webradio_development

test:
  <<: *default
  database: webradio_test


production:
  primary: &primary_production
    <<: *default
    database: webradio_production
  cache:
    <<: *primary_production
    database: webradio_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: webradio_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: webradio_production_cable
    migrations_paths: db/cable_migrate
