name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: |
        docker-compose -f docker-compose.test.yml up -d --build
        docker-compose -f docker-compose.test.yml ps
        docker-compose -f docker-compose.test.yml logs

    - name: prepare
      run: |
        docker-compose -f docker-compose.test.yml ps
        docker-compose -f docker-compose.test.yml logs
        docker-compose -f docker-compose.test.yml exec -T app bin/rails db:create --trace
        docker-compose -f docker-compose.test.yml exec -T app bin/rails db:test:prepare --trace

    - name: Run rubocop
      run: docker-compose -f docker-compose.test.yml exec -T app bundle exec rubocop

    - name: Run tests
      run: |
        docker-compose -f docker-compose.test.yml exec -e CI=true-T app bundle exec rspec .

    - name: Stop containers
      if: always()
      run: docker-compose -f docker-compose.test.yml down

   build-and-push:
     runs-on: ubuntu-latest
     needs: test
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v2
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@
     - name: Login to Docker Hub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

     - name: Build and push Docker image for ARM
       if: success()
       uses: docker/build-push-action@v2
       with:
         context: .
         file: ./Dockerfile
         platforms: linux/arm/v7
         push: true
         tags: |
           ${{ secrets.DOCKER_USERNAME }}/webradio:arm
           ${{ github.sha }}

     - name: Build and push Docker image for x86
       if: success()
       uses: docker/build-push-action@v2
       with:
         context: .
         file: ./Dockerfile
         platforms: linux/amd64
         push: true
         tags: |
           ${{ secrets.DOCKER_USERNAME }}/webradio:latest
           ${{ github.sha }}
